# Generated by Django 2.1.5 on 2019-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('location_hu', models.CharField(max_length=100)),
                ('location_en', models.CharField(max_length=100)),
                ('country_hu', models.CharField(max_length=50)),
                ('country_en', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='projects.ProjectImageModel'),
        ),
    ]
