# Generated by Django 2.1.5 on 2019-08-13 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='projectimagemodel',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
