# Generated by Django 2.1.5 on 2019-08-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190813_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
