# Generated by Django 2.1.5 on 2019-08-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190813_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='project',
            name='description_hu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
