# Generated by Django 2.1.5 on 2019-08-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190813_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.Project'),
        ),
    ]
