# Generated by Django 2.1.5 on 2019-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190813_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
