# Generated by Django 2.2.4 on 2019-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190816_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
