# Generated by Django 2.2.4 on 2019-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190818_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='Project page'),
        ),
    ]
