# Generated by Django 2.2.5 on 2019-09-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190907_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
