# Generated by Django 2.2.4 on 2019-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190817_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='description_hu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
