# Generated by Django 2.2.5 on 2019-10-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('info_hu', models.TextField()),
                ('info_en', models.TextField()),
            ],
        ),
    ]
