# Generated by Django 2.1.5 on 2019-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hu', models.TextField()),
                ('info_en', models.TextField()),
            ],
        ),
    ]
