# Generated by Django 2.2.4 on 2019-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_auto_20190812_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
