# Generated by Django 2.2.5 on 2019-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0003_slideshow_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='slideshow',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
