# Generated by Django 2.1.5 on 2019-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('subtitle_hu', models.CharField(max_length=200)),
                ('subtitle_en', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
